version: '3.8'

services:

  api:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        python manage.py migrate
        python manage.py collectstatic
        gunicorn dj_blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - '8000'
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: mysql:8.0
    container_name: mySql
    cap_add:
      - SYS_NICE
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - dbVol:/var/lib/mysql
      - ./dbVol/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/app/staticfiles
    depends_on:
      - api

volumes:
  static_volume:
  dbVol: